apiVersion: v1
kind: Service
metadata:
  name: {{ include "auvex.gateway.fullname" . }}
  labels:
    {{- include "auvex.componentLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "auvex.componentSelectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
