package com.auvex.gateway.audit;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * The data captured for one audited call.
 *
 * <p>The hash chain is taken over the core fields (see {@link AuditChain#canonical}); {@code
 * createdAt} is generated by the application so the hashed value matches the stored one. Only
 * redacted text appears here; raw PII must never reach it. Token counts and cost are present only
 * for completed non-streaming calls. {@code redactionCounts} (per-type masking tallies) is
 * analytics metadata and is intentionally outside the hash chain.
 */
public record AuditEntry(
    UUID tenantId,
    UUID requestId,
    String actor,
    String model,
    Verdict verdict,
    String promptRedacted,
    String responseRedacted,
    Instant createdAt,
    Integer promptTokens,
    Integer completionTokens,
    BigDecimal costUsd,
    Map<String, Integer> redactionCounts) {

  /** Convenience constructor for callers without token/cost/redaction data (streaming, tests). */
  public AuditEntry(
      UUID tenantId,
      UUID requestId,
      String actor,
      String model,
      Verdict verdict,
      String promptRedacted,
      String responseRedacted,
      Instant createdAt) {
    this(
        tenantId,
        requestId,
        actor,
        model,
        verdict,
        promptRedacted,
        responseRedacted,
        createdAt,
        null,
        null,
        null,
        Map.of());
  }
}
