package com.auvex.gateway.audit;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * The data captured for one audited call — exactly the fields the hash chain is taken over.
 *
 * <p>{@code createdAt} is generated by the application (not the database) so the value that is
 * hashed is the same value that is stored. Only redacted text appears here; raw PII must never
 * reach it. Token counts and cost are present only for completed non-streaming calls (null
 * otherwise).
 */
public record AuditEntry(
    UUID tenantId,
    UUID requestId,
    String actor,
    String model,
    Verdict verdict,
    String promptRedacted,
    String responseRedacted,
    Instant createdAt,
    Integer promptTokens,
    Integer completionTokens,
    BigDecimal costUsd) {

  /** Convenience constructor for callers without token/cost data (streaming, blocked, tests). */
  public AuditEntry(
      UUID tenantId,
      UUID requestId,
      String actor,
      String model,
      Verdict verdict,
      String promptRedacted,
      String responseRedacted,
      Instant createdAt) {
    this(
        tenantId,
        requestId,
        actor,
        model,
        verdict,
        promptRedacted,
        responseRedacted,
        createdAt,
        null,
        null,
        null);
  }
}
