package com.auvex.gateway.audit;

import java.time.Instant;
import java.util.UUID;

/**
 * The data captured for one audited call — exactly the fields the hash chain is taken over.
 *
 * <p>{@code createdAt} is generated by the application (not the database) so the value that is
 * hashed is the same value that is stored. Only redacted text appears here; raw PII must never
 * reach it.
 */
public record AuditEntry(
    UUID tenantId,
    UUID requestId,
    String actor,
    String model,
    Verdict verdict,
    String promptRedacted,
    String responseRedacted,
    Instant createdAt) {}
