package com.gatewise.gateway.audit;

import com.gatewise.gateway.auth.AuthenticatedTenant;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * The data captured for one audited call.
 *
 * <p>The hash chain is taken over the core fields (see {@link AuditChain#canonical}); {@code
 * createdAt} is generated by the application so the hashed value matches the stored one. Only
 * redacted text appears here; raw PII must never reach it. Token counts and cost are present only
 * for completed non-streaming calls. {@code redactionCounts} (per-type masking tallies) and the
 * {@code principal*} fields (who made the call) are analytics/attribution metadata and are
 * intentionally outside the hash chain, so adding them never breaks an existing chain.
 */
public record AuditEntry(
    UUID tenantId,
    UUID requestId,
    String actor,
    String model,
    Verdict verdict,
    String promptRedacted,
    String responseRedacted,
    Instant createdAt,
    Integer promptTokens,
    Integer completionTokens,
    BigDecimal costUsd,
    Map<String, Integer> redactionCounts,
    String principalType,
    UUID principalId,
    String principalEmail) {

  /**
   * Convenience constructor for callers that capture no principal yet (enriched later, or seed).
   */
  public AuditEntry(
      UUID tenantId,
      UUID requestId,
      String actor,
      String model,
      Verdict verdict,
      String promptRedacted,
      String responseRedacted,
      Instant createdAt,
      Integer promptTokens,
      Integer completionTokens,
      BigDecimal costUsd,
      Map<String, Integer> redactionCounts) {
    this(
        tenantId,
        requestId,
        actor,
        model,
        verdict,
        promptRedacted,
        responseRedacted,
        createdAt,
        promptTokens,
        completionTokens,
        costUsd,
        redactionCounts,
        null,
        null,
        null);
  }

  /** Convenience constructor for callers without token/cost/redaction data (streaming, tests). */
  public AuditEntry(
      UUID tenantId,
      UUID requestId,
      String actor,
      String model,
      Verdict verdict,
      String promptRedacted,
      String responseRedacted,
      Instant createdAt) {
    this(
        tenantId,
        requestId,
        actor,
        model,
        verdict,
        promptRedacted,
        responseRedacted,
        createdAt,
        null,
        null,
        null,
        Map.of());
  }

  /**
   * Returns a copy stamped with the acting principal, or {@code this} if there's nothing to add —
   * no principal bound, or one already recorded. Called on the request thread (where the principal
   * is known) so the attribution travels with the entry even when it's persisted asynchronously.
   */
  public AuditEntry withPrincipal(AuthenticatedTenant principal) {
    if (principal == null || principalType != null) {
      return this;
    }
    return new AuditEntry(
        tenantId,
        requestId,
        actor,
        model,
        verdict,
        promptRedacted,
        responseRedacted,
        createdAt,
        promptTokens,
        completionTokens,
        costUsd,
        redactionCounts,
        principal.principalType(),
        principal.principalId(),
        principal.memberEmail());
  }
}
